version: '3.8'

services:
  berniefm:
    build: .
    container_name: bernie-radio
    ports:
      - "8000:8000"  # Icecast stream
      - "8001:8001"  # API
    volumes:
      - ./bernie-radio-stream/data:/app/data
      - ./icecast-logs:/var/log/icecast2
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 